### ISSUE TITLE
用toDataURL获取不到LOGO内容,想把canvas变成img，数据中没有LOGO内容

### ISSUE THREAD

**Issue by ly-long** [JianmingXia/QRCodeJS#1]

**Comment by JianmingXia** [comment]
toDataURL的过程需要延后，直接toDataURL时，logo可能没有添加上去：
待渲染成功后：
![image](https://user-images.githubusercontent.com/9691577/28297344-f70af794-6b9f-11e7-85e0-cfc42be5f463.png)

**Comment by JianmingXia** [comment]
加logo的二维码目前无法直接使用img标签，原因是因为给二维码加图片Logo的时间是不可控的，二维码很快就渲染出来了，但是图片需要等待加载完成才能加上。

**Comment by ly-long** [comment]
好吧...但是不弄的IMG。这canvas拿来不好操作......

**Comment by JianmingXia** [comment]
使用qrcode_dev.js试试，这是我刚改的，可能不太稳定，传入use_canvas参数设置img or canvas渲染。[demo页面](https://github.com/JianmingXia/QRCodeJS/blob/master/Demo/cancas_to_img.html)

**Comment by ly-long** [comment]
不行，里面的toDataURL会报错的.

**Comment by JianmingXia** [comment]
错误信息能贴下么，我传上去代码，肯定是经过本地调试的：
![image](https://user-images.githubusercontent.com/9691577/28298790-e8455a26-6ba7-11e7-9464-4b694d7c3835.png)

**Comment by ly-long** [comment]
![_ _20170718110500](https://user-images.githubusercontent.com/28302478/28298978-08fe623e-6ba9-11e7-949e-f976c6c25855.png)

**Comment by ly-long** [comment]
我的logo是网络地址，不是本地图片

**Comment by JianmingXia** [comment]
这个问题很明显不是QRCodeJS的问题，[看这儿](https://stackoverflow.com/questions/20424279/canvas-todataurl-securityerror)。
本地图片会产生跨域问题，所以不能直接通过浏览器打开文件管理器，而是需要在本地配置下环境，使用127.0.0.1:端口访问：

![image](https://user-images.githubusercontent.com/9691577/28299226-93cc2206-6baa-11e7-945f-650d470a4a8b.png)

**Comment by JianmingXia** [comment]
不好意思，才看到你引用的网络图片，不过问题还是一样，网络图片会有跨域的问题，解决办法：
- 网络图片的源允许你跨域（此时配置的127.0.0.1是不被承认的，需要有实际域名）
- 引用不会产生跨域问题的图片

**Comment by ly-long** [comment]
图片是自己服务器的。。静态资源在本地跑。调的接口..这种咋办

**Comment by JianmingXia** [comment]
首先，我们确认这是一个图片的跨域问题，你将图片改成本地的图片肯定是能够加载的（比如放在你们的项目里面）。
- 如果你只是在本地做个demo，我觉得没有必要使用自己服务器的图片，使用本地的没问题；
- 另外可能就是你现在在做一个项目，需要引用服务器的图片。但是这个项目肯定是要发到线上的，现在有两个方法可以试试：
    - 将图片服务器设置全部可跨域（可能会有些不安全）
    - 尽快将项目上线，或者是先发一个简单的demo上去，配置域名，图片服务器设置可跨域域名，测试这个功能。

以上是我的经验，可以试试。

**Comment by ly-long** [comment]
我这是用VUE做的webapp。。代码会放本地。获取的使用户头像来生产二维码。---图片服务器设置全部可跨域---是配个请求头Access-Control-Allow-Origin: *么？

**Comment by JianmingXia** [comment]
我把生成头像理解为是一个服务，把服务挂载在本地，我觉得还是挺奇怪的。
关于跨域，是这么设置的。

**Comment by ly-long** [comment]
设置了这图貌似还是不能

**Comment by JianmingXia** [comment]
方便贴个图片的链接给我么，我可以调试下。

**Comment by ly-long** [comment]
https://develop.jinzhuzhu.com.cn/Uploads/Picture/9134720170718144549.png头像

**Comment by ly-long** [comment]
https://develop.jinzhuzhu.com.cn/Uploads/Picture/9134720170718144549.png

**Comment by JianmingXia** [comment]
我调试了下，还是提示跨域的问题。首先确认设置跨域是否有效。
不清楚会不会是本地服务器的问题，这块我也不是很清楚。

error:
- Access to Image at 'https://develop.jinzhuzhu.com.cn/Uploads/Picture/9134720170718144549.png' from origin 'http://test.qrcode.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://test.qrcode.com' is therefore not allowed access.

**Comment by JianmingXia** [comment]
设置可跨域后，会有这个response header头：
![image](https://user-images.githubusercontent.com/9691577/28306857-8af42ce0-6bd3-11e7-84b0-ad3c931d0036.png)
很明显，你提供给我的并没有：
![image](https://user-images.githubusercontent.com/9691577/28306875-9dff1c6e-6bd3-11e7-985d-84d3546f4ab9.png)

**Comment by ly-long** [comment]
...图片的跨域该在哪设置？

**Comment by ly-long** [comment]
接口都设置了

**Comment by JianmingXia** [comment]
这方面资料有很多，你可以在网上搜到的：

![image](https://user-images.githubusercontent.com/9691577/28307488-ab219d8e-6bd5-11e7-88de-9c0d8ccf0a4b.png)

跨域问题处理完后，qrcode_dev.js请换成最新的。
